git:
  submodules: false
language: php
cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"
php:
- 5.6
- 7.0
- 7.1
matrix:
  fast_finish: true
  include:
  - php: 7.0.12
    env: DB_CONNECTION=mysql DB_DATABASE=imotorist_test DB_USERNAME=root DB_PASSWORD=''
      DB_PORT=3306 EXEC_COVERAGE=true
    sudo: required
    dist: trusty
  exclude:
  - php: 5.6
    env: DB_CONNECTION=mysql DB_DATABASE=imotorist_test DB_USERNAME=root DB_PASSWORD=''
      DB_PORT=3306 EXEC_COVERAGE=true
  - php: 7.0
    env: DB_CONNECTION=mysql DB_DATABASE=imotorist_test DB_USERNAME=root DB_PASSWORD=''
      DB_PORT=3306 EXEC_COVERAGE=true
  - php: 7.1
    env: DB_CONNECTION=mysql DB_DATABASE=imotorist_test DB_USERNAME=root DB_PASSWORD=''
      DB_PORT=3306 EXEC_COVERAGE=true
  allow_failures:
  - env: DB_DATABASE=sqlite
  - php: 7.0.12
    env: DB_CONNECTION=mysql DB_DATABASE=imotorist_test DB_USERNAME=root DB_PASSWORD=''
      DB_PORT=3306 EXEC_COVERAGE=true
before_install:
- if [[ "$DB_CONNECTION" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS imotorist_test;"
  -U postgres; fi
- if [[ "$DB_CONNECTION" == "pgsql" ]]; then psql -c "create database imotorist_test;"
  -U postgres; fi
- if [[ "$DB_CONNECTION" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS
  imotorist_test;" -uroot; fi
env:
- DB_CONNECTION=mysql DB_DATABASE=imotorist_test DB_USERNAME=root DB_PASSWORD='' DB_PORT=3306
- DB_CONNECTION=pgsql DB_DATABASE=imotorist_test DB_USERNAME=postgres DB_PASSWORD=''
  DB_PORT=5432
- DB_CONNECTION=mysql DB_DATABASE=imotorist_test DB_USERNAME=root DB_PASSWORD='' DB_PORT=3306
  EXEC_COVERAGE=true
- DB_DATABASE=sqlite
before_script:
- if [[ $EXEC_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini ; fi
- if [[ $EXEC_COVERAGE = 'true' ]]; then echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv
  version-name)/etc/conf.d/travis.ini ; fi
- composer self-update || true
- composer install --dev --no-interaction -o --no-scripts
- composer run-script post-root-package-install
- composer run-script post-create-project-cmd
- composer run-script post-install-cmd
script:
- if [[ $EXEC_COVERAGE = 'true' ]]; then phpdbg -qrr ./vendor/bin/phpunit --coverage-clover=coverage.clover
  ; fi
- if [[ $EXEC_COVERAGE != 'true' ]]; then ./vendor/bin/phpunit ; fi
after_success:
- if [[ $EXEC_COVERAGE = 'true' ]]; then php vendor/bin/coveralls -v -x coverage.clover
  ; fi
after_failure:
- cat storage/logs/laravel-`date +"%Y-%m-%d"`.log
notifications:
  email: false
  slack: imotorist:tNnKlrzgtHK4CSLwkAvYfMA4
deploy:
  provider: heroku
  api_key:
    secure: rtYGbi1GtJ11+X2r+DTAWVJTNRh9INrbuIcSoFHMBWcMqYNbBfBhltcihdzkAO1RAqzHOwLuOVUd5h4EPetgaQypyLje6PZUEXCR6Tmf7teJk6q5OsUYBxr8HiwXiZFVc5WWTmEroS/ag+haNbPTdGDdjNRECpIBvbixw12J80WXoHu9fdkJuOAsbAFeyKoezCFMD1IZlOBWP+1OOyp0e3hg4m8Xa6IStG9tPBMJ8+qPnzn+OStNZPAiUP9D8ODgFlg5vYbulUmBVqbdmL5UL049EMQB7tjOYLQQEyx8AXqB1g+/Bo3JHKZkm/rWo0woKrPXUFt81f68BnQGEhuQPe4HTsDeG2DuotgTTKYV6NTVi1bA0PVbaWBYwPo5OovfBTgatbSXdFms2yaOmT7l+b0PiJwsucghbCaIB+KXb6it1U/7islqe9BbaO1mOX2ZDmZvGIFyF+lhJa4SfznGJ2yQjHEg4c68+oaE0a2aQRb++roTtFpHpF9BHIZoUVkDjj6YYi2xF/TpYBuBrNZPkDxAbu4jVBp+6JNj5rRcEQdumdXAUfeSYiG6qQi+O1lavJM1rAjsAx38xeHBAh49qeamF3f85h5yb7/vn663yGqDt5sEHfE/2TNYcwe+iWqOd3RcnvlK8iaefvqDDd7mhS2UG8l8MJt4aY8J2PQF2y0=
  app:
    master: imotorist-prod
    develop: imotorist-stage
  run:
    - "php artisan migrate --seed"
